patch_notifications_enabled: false

patch_notify_from_email: "xxxx@example.com"

patch_notify_to_emails:
  - "xxx@example.com"
  - "xxy@example.com"
  - "xxz@example.com"

patch_notify_cc_emails:
  - "xxx@example.com"
  - "xxy@example.com"
  - "xxz@example.com"


# TODO: update config file to have structure like:
# applications:
#  - name: apache
#    ip_regex: "^((XX\.XX\.XX\.)|(XX\.XX\.XX\.))\d{1,3}$"
#    start_steps:
#       - "sudo service start stop"
#    stop_steps:
#       - "sudo service apache2 stop"
#    health_check:
#       command: "curl -s -o /dev/null -w \"%{http_code}\" http://localhost:80"
#       num_retries: 2
#       timeout: 10m
#  - name: backend
#    ip_regex: "^((XX\.XX\.XX\.)|(XX\.XX\.XX\.))\d{1,3}$"
#  - name: web
#    ip_regex: "^((XX\.XX\.XX\.)|(XX\.XX\.XX\.))\d{1,3}$"
